title: An introduction to data science
logo: /images/goldenretriever_logo.png
description: A website to learn about the useful and interesting world of data science.
show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal
