remote_theme: just-the-docs/just-the-docs
title: An introduction to data science
logo: /images/goldenretriever_logo.png
description: A website to learn about the useful and interesting world of data science.
aux_links:
  "Materials on GitHub":
    - "//github.com/crsl/learning-data-science"
footer_content: "Copyright Solis-Lemus lab &copy; 2023. Distributed by an <a href=\"https://github.com/crsl4/learning-data-science/tree/master/LICENSE\">MIT license.</a>"
exclude:
   - readme.md
   - code/
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  key:
    title: Key
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
compress_html:
  blanklines: true
# LaTeX rendering via "katex" (KaTeX, default) or "mathjax" (MathJax) or "none" / "off" (NO rendering)
# https://github.com/just-the-docs/just-the-docs/issues/198
latex: katex
